version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
      - "443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3,ecs,route53,kms,iam,logs
      - DEBUG=${DEBUG:-0}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  docker_ssh_openvpn:
    container_name: docker_ssh_openvpn
    cap_add:
      - NET_ADMIN
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
      - "2222:2222"
    environment:
      - port_override=9999
      - protocol_override=udp
      - ipv4_override=127.0.0.1
      - ipv6_override=
      - initial_client_name_override=client
