#!/bin/sh
# /etc/init.d/openvpn
### BEGIN INIT INFO
# Provides:          openvpn
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OpenVPN Server service
### END INIT INFO

case "$1" in
  start)
    if [ -e /var/run/openvpn.pid ]; then
      echo "OpenVPN is already running"
      exit 1
    fi

    if [ ! -e /etc/openvpn/server/server.conf ]; then
      echo "OpenVPN server configuration not found"
      exit 1
    fi

    cd /etc/openvpn/server
    echo "Starting OpenVPN"
    /usr/sbin/openvpn --config /etc/openvpn/server/server.conf
    ;;
  stop)
    echo "Stopping OpenVPN"
    killall openvpn
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0